name: build-action
description: build action
runs:
  using: composite
  steps:
    - name: Build project
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        dotnet build -c Release
