name: test-action
description: test action
runs:
  using: composite
  steps:
    - name: Check format
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        dotnet format --severity info --verify-no-changes
    - name: Test project
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        dotnet test -c Release -v quiet -l "console;verbosity=normal"